import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  'https://cvazyvdxnjmoenasavvq.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2YXp5dmR4bmptb2VuYXNhdnZxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3Mzg5ODU3MywiZXhwIjoyMDg5NDc0NTczfQ.oeQFsIfGewelt77Jy66zy2tALex0EWtNBATMqWA6mZc'
)

const DEPT_ID = '00000000-0000-0000-0000-000000000001'

const STAFF = [
  { name: 'Dr. Sharmila VJ',          email: 'hodcse@licet.ac.in',           password: 'licet@sharmila',       role: 'HOD',       empId: 'FAC001' },
  { name: 'Dr. Remegius Praveen L',   email: 'reme@licet.ac.in',             password: 'licet@reme',           role: 'PROFESSOR', empId: 'FAC002' },
  { name: 'Dr. Arulmozhi P',          email: 'arulmozhi.p@licet.ac.in',      password: 'licet@arulmozhi',      role: 'PROFESSOR', empId: 'FAC003' },
  { name: 'Dr. Gopalakrishnan K',     email: 'drgk81@licet.ac.in',           password: 'licet@gopalakrishnan', role: 'PROFESSOR', empId: 'FAC004' },
  { name: 'Dr. Sharmila VJ Member',  email: 'sharmila.vj@licet.ac.in',      password: 'licet@sharmila',       role: 'PROFESSOR', empId: 'FAC005' },
  { name: 'Dr. Jainish GR',           email: 'jainish.gr@licet.ac.in',       password: 'licet@jainish',        role: 'PROFESSOR', empId: 'FAC006' },
  { name: 'Ms. Delphy P',             email: 'delphy.p@licet.ac.in',         password: 'licet@delphy',         role: 'PROFESSOR', empId: 'FAC007' },
  { name: 'Ms. Freesie Greta L',      email: 'freesiegreta.l@licet.ac.in',   password: 'licet@freesie',        role: 'PROFESSOR', empId: 'FAC008' },
  { name: 'Ms. Jeevitha A',           email: 'jeevitha.a@licet.ac.in',       password: 'licet@jeevitha',       role: 'PROFESSOR', empId: 'FAC009' },
  { name: 'Ms. Sathia Priya R',       email: 'sathiapriya.r@licet.ac.in',    password: 'licet@sathia',         role: 'PROFESSOR', empId: 'FAC010' },
  { name: 'Ms. Daya Mary Mathew',     email: 'dayamarymathew@licet.ac.in',   password: 'licet@daya',           role: 'PROFESSOR', empId: 'FAC011' },
  { name: 'Ms. Accelia S',            email: 'accelia.s@licet.ac.in',        password: 'licet@accelia',        role: 'PROFESSOR', empId: 'FAC012' },
  { name: 'Ms. Priya A',              email: 'priya.a@licet.ac.in',          password: 'licet@priya',          role: 'PROFESSOR', empId: 'FAC013' },
  { name: 'Ms. Reshma M',             email: 'reshma.m@licet.ac.in',         password: 'licet@reshma',         role: 'PROFESSOR', empId: 'FAC014' },
  { name: 'Ms. Shirly Sudhakaran',    email: 'shirlysudhakaran@licet.ac.in', password: 'licet@shirly',         role: 'PROFESSOR', empId: 'FAC015' },
  { name: 'Ms. Limsa Joshi',          email: 'limsajoshi@licet.ac.in',       password: 'licet@limsa',          role: 'PROFESSOR', empId: 'FAC016' },
  { name: 'Ms. Nirmala Santiago',     email: 'iqac@licet.ac.in',             password: 'licet@nirmala',        role: 'PROFESSOR', empId: 'FAC017' },
]

const STUDENTS = [
  // I CSE-A
  { name: 'Abisha Rose S', email: 'abisharose.29csa@licet.ac.in', password: 'abisharose29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Abraham Nazarene A', email: 'abrahamnazarene.29csa@licet.ac.in', password: 'abrahamnazarene29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Adhi S', email: 'adhi.29csa@licet.ac.in', password: 'adhi29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Akshaya P', email: 'akshayap.29csa@licet.ac.in', password: 'akshayap29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Akshaya T', email: 'akshayat.29csa@licet.ac.in', password: 'akshayat29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Alwin Gerard A', email: 'alwingerard.29csa@licet.ac.in', password: 'alwingerard29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Anandhi E', email: 'anandhi.29csa@licet.ac.in', password: 'anandhi29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Angel Mathew', email: 'angelmathew.29csa@licet.ac.in', password: 'angelmathew29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Anika Sharon S', email: 'anikasharon.29csa@licet.ac.in', password: 'anikasharon29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Anto Jeevan A', email: 'antojeevan.29csa@licet.ac.in', password: 'antojeevan29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Anto Rozik B', email: 'antorozik.29csa@licet.ac.in', password: 'antorozik29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Arockiya Mithushan S', email: 'arockiyamithushan.29csa@licet.ac.in', password: 'arockiyamithushan29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Ashrit Kaleswar B', email: 'ashritkaleswar.29csa@licet.ac.in', password: 'ashritkaleswar29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Ashwanth S', email: 'ashwanth.29csa@licet.ac.in', password: 'ashwanth29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Asir Arivazhagan M', email: 'asirarivazhagan.29csa@licet.ac.in', password: 'asirarivazhagan29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Auslis Jackshine S V', email: 'auslisjackshine.29csa@licet.ac.in', password: 'auslisjackshine29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Azeem Ashiq S R', email: 'azeemashiq.29csa@licet.ac.in', password: 'azeemashiq29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Balmar Collins P', email: 'balmarcollins.29csa@licet.ac.in', password: 'balmarcollins29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Beniyel Velankanni C', email: 'beniyelvelankanni.29csa@licet.ac.in', password: 'beniyelvelankanni29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Bhavesh Honorius K R', email: 'bhaveshhonorius.29csa@licet.ac.in', password: 'bhaveshhonorius29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Blessy Peniel V', email: 'blessypeniel.29csa@licet.ac.in', password: 'blessypeniel29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Celestin Vincia A', email: 'celestinvincia.29csa@licet.ac.in', password: 'celestinvincia29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Charvi A', email: 'charvi.29csa@licet.ac.in', password: 'charvi29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Cheryl Winona Anand', email: 'cherylwinonaanand.29csa@licet.ac.in', password: 'cherylwinonaanand29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Chezhiyan P', email: 'chezhiyan.29csa@licet.ac.in', password: 'chezhiyan29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Chris Allwyn J', email: 'chrisallwyn.29csa@licet.ac.in', password: 'chrisallwyn29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Christ Theepshika T', email: 'christtheepshika.29csa@licet.ac.in', password: 'christtheepshika29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Danushree P', email: 'danushree.29csa@licet.ac.in', password: 'danushree29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Dhia Reanna J A', email: 'dhiareanna.29csa@licet.ac.in', password: 'dhiareanna29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Dhivya G', email: 'dhivya.29csa@licet.ac.in', password: 'dhivya29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Gopika S', email: 'gopika.29csa@licet.ac.in', password: 'gopika29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Gospel H', email: 'gospel.29csa@licet.ac.in', password: 'gospel29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Haldrin R', email: 'haldrin.29csa@licet.ac.in', password: 'haldrin29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Hannah Kiruba D', email: 'hannahkiruba.29csa@licet.ac.in', password: 'hannahkiruba29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Hari Hara Perumal G', email: 'hariharaperumal.29csa@licet.ac.in', password: 'hariharaperumal29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Hementh D M', email: 'hementh.29csa@licet.ac.in', password: 'hementh29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Henry Prabhu J', email: 'henryprabhu.29csa@licet.ac.in', password: 'henryprabhu29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Jane Shirley A', email: 'janeshirley.29csa@licet.ac.in', password: 'janeshirley29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Janet Jeffrin P A', email: 'janetjeffrin.29csa@licet.ac.in', password: 'janetjeffrin29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Jasmine Jermina S', email: 'jasminejermina.29csa@licet.ac.in', password: 'jasminejermina29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Jassicl J', email: 'jassicl.29csa@licet.ac.in', password: 'jassicl29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Jayaseelan S', email: 'jayaseelan.29csa@licet.ac.in', password: 'jayaseelan29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Jeevan Roche J', email: 'jeevanroche.29csa@licet.ac.in', password: 'jeevanroche29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Jennifer Maria Mcenroe Michael', email: 'jennifermariamcenroemichael.29csa@licet.ac.in', password: 'jennifermariamcenroemichael29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Jeraffin Femina A', email: 'jeraffinfemina.29csa@licet.ac.in', password: 'jeraffinfemina29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Jerina S', email: 'jerina.29csa@licet.ac.in', password: 'jerina29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Jerry Elvis M', email: 'jerryelvis.29csa@licet.ac.in', password: 'jerryelvis29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Jesmitha Mary S', email: 'jesmithamary.29csa@licet.ac.in', password: 'jesmithamary29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Joavan Paldano G', email: 'joavanpaldano.29csa@licet.ac.in', password: 'joavanpaldano29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Joe Daria A', email: 'joedaria.29csa@licet.ac.in', password: 'joedaria29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Joel Alfred A', email: 'joelalfred.29csa@licet.ac.in', password: 'joelalfred29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'John Rithickson A', email: 'johnrithickson.29csa@licet.ac.in', password: 'johnrithickson29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Joolie Margaret L', email: 'jooliemargaret.29csa@licet.ac.in', password: 'jooliemargaret29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Joshua Antony J', email: 'joshuaantony.29csa@licet.ac.in', password: 'joshuaantony29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Joshua Raj U', email: 'joshuaraj.29csa@licet.ac.in', password: 'joshuaraj29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Jothilakshmi R', email: 'jothilakshmi.29csa@licet.ac.in', password: 'jothilakshmi29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Joywyn Samuel S', email: 'joywynsamuel.29csa@licet.ac.in', password: 'joywynsamuel29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Kadhirvel G', email: 'kadhirvel.29csa@licet.ac.in', password: 'kadhirvel29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Kalidoss KR', email: 'kalidoss.29csa@licet.ac.in', password: 'kalidoss29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Karthik Raja N', email: 'karthikraja.29csa@licet.ac.in', password: 'karthikraja29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Kathie Johanna', email: 'kathiejohanna.29csa@licet.ac.in', password: 'kathiejohanna29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Kavya K', email: 'kavya.29csa@licet.ac.in', password: 'kavya29csa@licet', section: 'I CSE-A', year: 1 },
  { name: 'Keaton Kinsley LVR', email: 'keatonkinsley.29csa@licet.ac.in', password: 'keatonkinsley29csa@licet', section: 'I CSE-A', year: 1 },
  // I CSE-B
  { name: 'Joshua Nicolas R', email: 'joshuanicolas.29csb@licet.ac.in', password: 'joshuanicolas29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Kevin Bosco V', email: 'kevinbosco.29csb@licet.ac.in', password: 'kevinbosco29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Kevin Gerald L', email: 'kevingerald.29csb@licet.ac.in', password: 'kevingerald29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Kevin Lawrence I', email: 'kevinlawrence.29csb@licet.ac.in', password: 'kevinlawrence29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Kevinsan A', email: 'kevinsan.29csb@licet.ac.in', password: 'kevinsan29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Kewin Idhayanathan P', email: 'kewinidhayanathan.29csb@licet.ac.in', password: 'kewinidhayanathan29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Keziya Jenifer S', email: 'keziyajenifer.29csb@licet.ac.in', password: 'keziyajenifer29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Krithickmukesh', email: 'krithickmukesh.29csb@licet.ac.in', password: 'krithickmukesh29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Lanish Joshwa A', email: 'lanishjoshwa.29csb@licet.ac.in', password: 'lanishjoshwa29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Madhuragavi G', email: 'madhuragavi.29csb@licet.ac.in', password: 'madhuragavi29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Maheshwaran K', email: 'maheshwaran.29csb@licet.ac.in', password: 'maheshwaran29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Mahizha I', email: 'mahizha.29csb@licet.ac.in', password: 'mahizha29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Manikandan S', email: 'manikandan.29csb@licet.ac.in', password: 'manikandan29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Maria Arul Varun X', email: 'mariaarulvarun.29csb@licet.ac.in', password: 'mariaarulvarun29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Mohammed Ashfaq A', email: 'mohammedashfaq.29csb@licet.ac.in', password: 'mohammedashfaq29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Monisha AK', email: 'monisha.29csb@licet.ac.in', password: 'monisha29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Morisha Maci V S', email: 'morishamaci.29csb@licet.ac.in', password: 'morishamaci29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Nanisha Josephine J', email: 'nanishajosephine.29csb@licet.ac.in', password: 'nanishajosephine29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Nelcy Sherlin J', email: 'nelcysherlin.29csb@licet.ac.in', password: 'nelcysherlin29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Nikil Roshan E', email: 'nikilroshan.29csb@licet.ac.in', password: 'nikilroshan29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Nikita Navanjali Abigail N', email: 'nikitanavanjaliabigail.29csb@licet.ac.in', password: 'nikitanavanjaliabigail29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Niranjana M', email: 'niranjana.29csb@licet.ac.in', password: 'niranjana29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Noel Joycy V', email: 'noeljoycy.29csb@licet.ac.in', password: 'noeljoycy29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Pallapati Vijaya Vidisha', email: 'pallapativijayavidisha.29csb@licet.ac.in', password: 'pallapativijayavidisha29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Philip Alwin S', email: 'philipalwin.29csb@licet.ac.in', password: 'philipalwin29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Prince K', email: 'prince.29csb@licet.ac.in', password: 'prince29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Pritha K', email: 'pritha.29csb@licet.ac.in', password: 'pritha29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Priya Jecintha B', email: 'priyajecintha.29csb@licet.ac.in', password: 'priyajecintha29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Priyadharshan P', email: 'priyadharshan.29csb@licet.ac.in', password: 'priyadharshan29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Ragavi B', email: 'ragavi.29csb@licet.ac.in', password: 'ragavi29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Rathinavel B', email: 'rathinavel.29csb@licet.ac.in', password: 'rathinavel29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Riyana D', email: 'riyana.29csb@licet.ac.in', password: 'riyana29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Roselin Banu S', email: 'roselinbanu.29csb@licet.ac.in', password: 'roselinbanu29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Roshan A', email: 'roshan.29csb@licet.ac.in', password: 'roshan29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Sai Shrruthi K R', email: 'saishrruthi.29csb@licet.ac.in', password: 'saishrruthi29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Sajin P', email: 'sajin.29csb@licet.ac.in', password: 'sajin29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Sakthi K', email: 'sakthi.29csb@licet.ac.in', password: 'sakthi29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Sam C', email: 'sam.29csb@licet.ac.in', password: 'sam29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Sanjay P L', email: 'sanjaypl.29csb@licet.ac.in', password: 'sanjaypl29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Sanjay S', email: 'sanjays.29csb@licet.ac.in', password: 'sanjays29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Saro Hepsiba A', email: 'sarohepsiba.29csb@licet.ac.in', password: 'sarohepsiba29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Selina Bennet A', email: 'selinabennet.29csb@licet.ac.in', password: 'selinabennet29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Sesha Sai N', email: 'seshasai.29csb@licet.ac.in', password: 'seshasai29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Sharin Macreena N L', email: 'sharinmacreena.29csb@licet.ac.in', password: 'sharinmacreena29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Sharon Jessica C', email: 'sharonjessica.29csb@licet.ac.in', password: 'sharonjessica29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Silva J', email: 'silva.29csb@licet.ac.in', password: 'silva29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Sree Aishwin Raj S', email: 'sreeaishwinraj.29csb@licet.ac.in', password: 'sreeaishwinraj29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Srinivasakandan R', email: 'srinivasakandan.29csb@licet.ac.in', password: 'srinivasakandan29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Stalin A', email: 'stalin.29csb@licet.ac.in', password: 'stalin29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Solomon Antony J', email: 'solomonantony.29csb@licet.ac.in', password: 'solomonantony29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Tharsiga M', email: 'tharsiga.29csb@licet.ac.in', password: 'tharsiga29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Thiyagarasan C', email: 'thiyagarasan.29csb@licet.ac.in', password: 'thiyagarasan29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Trina Michelle J', email: 'trinamichelle.29csb@licet.ac.in', password: 'trinamichelle29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Twinkle Janet R', email: 'twinklejanet.29csb@licet.ac.in', password: 'twinklejanet29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Vaishnavi R', email: 'vaishnavi.29csb@licet.ac.in', password: 'vaishnavi29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Vanithalakshmi P', email: 'vanithalakshmi.29csb@licet.ac.in', password: 'vanithalakshmi29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Vedha Leo', email: 'vedhaleo.29csb@licet.ac.in', password: 'vedhaleo29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Vibin I A', email: 'vibin.29csb@licet.ac.in', password: 'vibin29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Vishal R', email: 'vishal.29csb@licet.ac.in', password: 'vishal29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Yajas Nitin S', email: 'yajasnitin.29csb@licet.ac.in', password: 'yajasnitin29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Yamini M', email: 'yamini.29csb@licet.ac.in', password: 'yamini29csb@licet', section: 'I CSE-B', year: 1 },
  { name: 'Youva Shree R', email: 'youvashree.29csb@licet.ac.in', password: 'youvashree29csb@licet', section: 'I CSE-B', year: 1 },
  // II CSE-A
  { name: 'Aagasri R', email: 'aagasri.28csa@licet.ac.in', password: 'aagasri28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Abhijeet V S', email: 'abhijeet.28csa@licet.ac.in', password: 'abhijeet28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Aishwarya S', email: 'aishwarya.28csa@licet.ac.in', password: 'aishwarya28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Aishwarya V S', email: 'aishwaryavs.28csa@licet.ac.in', password: 'aishwaryavs28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Amalya Grace A', email: 'amalyagrace.28csa@licet.ac.in', password: 'amalyagrace28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Andrea J B', email: 'andrea.28csa@licet.ac.in', password: 'andrea28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Angelin Ezhil Jegath C', email: 'angelinezhiljegath.28csa@licet.ac.in', password: 'angelinezhiljegath28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Anish Joseph Leo R', email: 'anishjosephleo.28csa@licet.ac.in', password: 'anishjosephleo28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Antany Ricky K', email: 'antanyricky.28csa@licet.ac.in', password: 'antanyricky28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Anto Snowin Y', email: 'antosnowin.28csa@licet.ac.in', password: 'antosnowin28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Anusha Agnes I', email: 'anushaagnes.28csa@licet.ac.in', password: 'anushaagnes28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Arlin Bins Mathew', email: 'arlinbinsmathew.28csa@licet.ac.in', password: 'arlinbinsmathew28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Arockia Mithuna Nimso N', email: 'arockiamithunanimso.28csa@licet.ac.in', password: 'arockiamithunanimso28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Arul Henin A', email: 'arulhenin.28csa@licet.ac.in', password: 'arulhenin28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Asen Castro A', email: 'asencastro.28csa@licet.ac.in', password: 'asencastro28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Asvitha J', email: 'asvitha.28csa@licet.ac.in', password: 'asvitha28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Athulya R', email: 'athulya.28csa@licet.ac.in', password: 'athulya28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Bavadharani B', email: 'bavadharani.28csa@licet.ac.in', password: 'bavadharani28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Bharani Dharan V', email: 'bharanidharan.28csa@licet.ac.in', password: 'bharanidharan28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Caitlyn Georgina L', email: 'caitlyngeorgina.28csa@licet.ac.in', password: 'caitlyngeorgina28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Castro Tamizh Selvan M', email: 'castrotamizhselvan.28csa@licet.ac.in', password: 'castrotamizhselvan28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Chris Benedict Patrick', email: 'chrisbenedictpatrick.28csa@licet.ac.in', password: 'chrisbenedictpatrick28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Christina Moses', email: 'christinamoses.28csa@licet.ac.in', password: 'christinamoses28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Daniel Ienigo S', email: 'danielienigo.28csa@licet.ac.in', password: 'danielienigo28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Dhanush', email: 'dhanush.28csa@licet.ac.in', password: 'dhanush28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Evangelina Merlin J', email: 'evangelinamerlin.28csa@licet.ac.in', password: 'evangelinamerlin28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Fathima Ameena Nisma N', email: 'fathimaameenanisma.28csa@licet.ac.in', password: 'fathimaameenanisma28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Felix Palraj B', email: 'felixpalraj.28csa@licet.ac.in', password: 'felixpalraj28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Ferdina R', email: 'ferdina.28csa@licet.ac.in', password: 'ferdina28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Francis Jeevaprakasham', email: 'francisjeevaprakasham.28csa@licet.ac.in', password: 'francisjeevaprakasham28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'George Fernandas X', email: 'georgefernandas.28csa@licet.ac.in', password: 'georgefernandas28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Gillian Rozario', email: 'gillianrozario.28csa@licet.ac.in', password: 'gillianrozario28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Glady J', email: 'glady.28csa@licet.ac.in', password: 'glady28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Goldwin R Jaffee', email: 'goldwinrjaffee.28csa@licet.ac.in', password: 'goldwinrjaffee28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Gokul Krishna Moorthy A', email: 'gokulkrishnamoorthy.28csa@licet.ac.in', password: 'gokulkrishnamoorthy28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Hanston Thomas Fernando H', email: 'hanstonthomasfernando.28csa@licet.ac.in', password: 'hanstonthomasfernando28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Haric Bravlin P', email: 'haricbravlin.28csa@licet.ac.in', password: 'haricbravlin28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Harinisri K', email: 'harinisri.28csa@licet.ac.in', password: 'harinisri28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Harsha Priyan K', email: 'harshapriyan.28csa@licet.ac.in', password: 'harshapriyan28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Harshal John V', email: 'harshaljohn.28csa@licet.ac.in', password: 'harshaljohn28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Hemila Rose A', email: 'hemilarose.28csa@licet.ac.in', password: 'hemilarose28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Jan Shafin J', email: 'janshafin.28csa@licet.ac.in', password: 'janshafin28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Jason Mathew P', email: 'jasonmathew.28csa@licet.ac.in', password: 'jasonmathew28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Jaya Aswin A', email: 'jayaaswin.28csa@licet.ac.in', password: 'jayaaswin28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Jeemol Mary Fredrick', email: 'jeemolmaryfredrick.28csa@licet.ac.in', password: 'jeemolmaryfredrick28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Jeeva Gheno J', email: 'jeevagheno.28csa@licet.ac.in', password: 'jeevagheno28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Jeevith E', email: 'jeevith.28csa@licet.ac.in', password: 'jeevith28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Jeff Thomson J', email: 'jeffthomson.28csa@licet.ac.in', password: 'jeffthomson28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Jeffrey Figo J', email: 'jeffreyfigo.28csa@licet.ac.in', password: 'jeffreyfigo28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Jefrin Dona S', email: 'jefrindona.28csa@licet.ac.in', password: 'jefrindona28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Jefrin M S A', email: 'jefrin.28csa@licet.ac.in', password: 'jefrin28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Jeriks Giftson J', email: 'jeriksgiftson.28csa@licet.ac.in', password: 'jeriksgiftson28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Jerocin A', email: 'jerocin.28csa@licet.ac.in', password: 'jerocin28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Jeroline R', email: 'jeroline.28csa@licet.ac.in', password: 'jeroline28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Jerome Antone J', email: 'jeromeantone.28csa@licet.ac.in', password: 'jeromeantone28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Joe Naren A', email: 'joenaren.28csa@licet.ac.in', password: 'joenaren28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Joel Nitin M', email: 'joelnitin.28csa@licet.ac.in', password: 'joelnitin28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'John Alistair', email: 'johnalistair.28csa@licet.ac.in', password: 'johnalistair28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'John Bosco J', email: 'johnbosco.28csa@licet.ac.in', password: 'johnbosco28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Joshiya C', email: 'joshiya.28csa@licet.ac.in', password: 'joshiya28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Joshua A', email: 'joshua.28csa@licet.ac.in', password: 'joshua28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Jothimani D', email: 'jothimani.28csa@licet.ac.in', password: 'jothimani28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Karthika K', email: 'karthika.28csa@licet.ac.in', password: 'karthika28csa@licet', section: 'II CSE-A', year: 2 },
  { name: 'Kaviya J', email: 'kaviya.28csa@licet.ac.in', password: 'kaviya28csa@licet', section: 'II CSE-A', year: 2 },
  // II CSE-B
  { name: 'Kevin Jose B', email: 'kevinjose.28csb@licet.ac.in', password: 'kevinjose28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Kisha Cicily S', email: 'kishacicily.28csb@licet.ac.in', password: 'kishacicily28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Kokila S', email: 'kokila.28csb@licet.ac.in', password: 'kokila28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Krifen Kenrich Fernando P', email: 'krifenkenrichfernando.28csb@licet.ac.in', password: 'krifenkenrichfernando28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Lathika Valli M', email: 'lathikavalli.28csb@licet.ac.in', password: 'lathikavalli28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Livinius Christy Raj L', email: 'liviniuschristyraj.28csb@licet.ac.in', password: 'liviniuschristyraj28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Mabel Mercita P', email: 'mabelmercita.28csb@licet.ac.in', password: 'mabelmercita28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Meldan Roy M', email: 'meldanroy.28csb@licet.ac.in', password: 'meldanroy28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Mereena Stanly', email: 'mereenastanly.28csb@licet.ac.in', password: 'mereenastanly28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Meril Joby', email: 'meriljoby.28csb@licet.ac.in', password: 'meriljoby28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Merlin Sharon A', email: 'merlinsharon.28csb@licet.ac.in', password: 'merlinsharon28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Mithilesh K S', email: 'mithilesh.28csb@licet.ac.in', password: 'mithilesh28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Mohamed Kaif S A', email: 'mohamedkaif.28csb@licet.ac.in', password: 'mohamedkaif28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Mohammed Aasim T A', email: 'mohammedaasim.28csb@licet.ac.in', password: 'mohammedaasim28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Mohan M', email: 'mohan.28csb@licet.ac.in', password: 'mohan28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Mutharasi M', email: 'mutharasi.28csb@licet.ac.in', password: 'mutharasi28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Mahalakshmi S', email: 'mahalakshmi.28csb@licet.ac.in', password: 'mahalakshmi28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Narayanaswamy C', email: 'narayanaswamy.28csb@licet.ac.in', password: 'narayanaswamy28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Naveenraj A', email: 'naveenraj.28csb@licet.ac.in', password: 'naveenraj28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Nithin Raj V', email: 'nithinraj.28csb@licet.ac.in', password: 'nithinraj28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Nithish Kumar P', email: 'nithishkumar.28csb@licet.ac.in', password: 'nithishkumar28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Nixon Immanuel Motha', email: 'nixonimmanuelmotha.28csb@licet.ac.in', password: 'nixonimmanuelmotha28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Nougotlu Lokesh', email: 'nougotlulokesh.28csb@licet.ac.in', password: 'nougotlulokesh28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Padmashree P', email: 'padmashree.28csb@licet.ac.in', password: 'padmashree28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Parthipan M', email: 'parthipan.28csb@licet.ac.in', password: 'parthipan28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Paul Nihil P', email: 'paulnihil.28csb@licet.ac.in', password: 'paulnihil28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Ponram P', email: 'ponram.28csb@licet.ac.in', password: 'ponram28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Pranathi J', email: 'pranathi.28csb@licet.ac.in', password: 'pranathi28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Prasanna R', email: 'prasanna.28csb@licet.ac.in', password: 'prasanna28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Praveen Raj P', email: 'praveenraj.28csb@licet.ac.in', password: 'praveenraj28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Prince Arockiaraj Ravi Selvem', email: 'princearockiarajraviselvem.28csb@licet.ac.in', password: 'princearockiarajraviselvem28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Pritheesh S M', email: 'pritheesh.28csb@licet.ac.in', password: 'pritheesh28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Prithika R', email: 'prithika.28csb@licet.ac.in', password: 'prithika28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Punitha R', email: 'punitha.28csb@licet.ac.in', password: 'punitha28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Priyadharshan V', email: 'priyadharshan.28csb@licet.ac.in', password: 'priyadharshan28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Rahul A', email: 'rahul.28csb@licet.ac.in', password: 'rahul28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Rakesh G', email: 'rakesh.28csb@licet.ac.in', password: 'rakesh28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Ranjitham K', email: 'ranjitham.28csb@licet.ac.in', password: 'ranjitham28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Rebacca A', email: 'rebacca.28csb@licet.ac.in', password: 'rebacca28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Rehaan Rafael John', email: 'rehaanrafaeljohn.28csb@licet.ac.in', password: 'rehaanrafaeljohn28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Rena Roy V S', email: 'renaroy.28csb@licet.ac.in', password: 'renaroy28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Rex John Abraham', email: 'rexjohnabraham.28csb@licet.ac.in', password: 'rexjohnabraham28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Rimy John', email: 'rimyjohn.28csb@licet.ac.in', password: 'rimyjohn28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Rithiga B', email: 'rithiga.28csb@licet.ac.in', password: 'rithiga28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Rithish R', email: 'rithish.28csb@licet.ac.in', password: 'rithish28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Roshan A', email: 'roshan.28csb@licet.ac.in', password: 'roshan28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Sadha', email: 'sadha.28csb@licet.ac.in', password: 'sadha28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Sam Godwin E', email: 'samgodwin.28csb@licet.ac.in', password: 'samgodwin28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Sam Joel Raj A', email: 'samjoelraj.28csb@licet.ac.in', password: 'samjoelraj28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Samsaron A', email: 'samsaron.28csb@licet.ac.in', password: 'samsaron28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Sangamitha V', email: 'sangamitha.28csb@licet.ac.in', password: 'sangamitha28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Sanjana C M', email: 'sanjana.28csb@licet.ac.in', password: 'sanjana28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Santhosh Babu E', email: 'santhoshbabu.28csb@licet.ac.in', password: 'santhoshbabu28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Santhosh K', email: 'santhosh.28csb@licet.ac.in', password: 'santhosh28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Savari Lidiya J', email: 'savarilidiya.28csb@licet.ac.in', password: 'savarilidiya28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Shailendra Saran S', email: 'shailendrasaran.28csb@licet.ac.in', password: 'shailendrasaran28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Shanna Remigius', email: 'shannaremigius.28csb@licet.ac.in', password: 'shannaremigius28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Shivani P S', email: 'shivani.28csb@licet.ac.in', password: 'shivani28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Shreya Angelina Prabhu', email: 'shreyaangelinaprabhu.28csb@licet.ac.in', password: 'shreyaangelinaprabhu28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Siva Priya R', email: 'sivapriya.28csb@licet.ac.in', password: 'sivapriya28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Smirthi A R', email: 'smirthi.28csb@licet.ac.in', password: 'smirthi28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Steffy Christina B', email: 'steffychristina.28csb@licet.ac.in', password: 'steffychristina28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Strachan Caemerrer J', email: 'strachancaemerrer.28csb@licet.ac.in', password: 'strachancaemerrer28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Sujith J', email: 'sujith.28csb@licet.ac.in', password: 'sujith28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Tanisha S', email: 'tanisha.28csb@licet.ac.in', password: 'tanisha28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Tressie Joshna C', email: 'tressiejoshna.28csb@licet.ac.in', password: 'tressiejoshna28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Uma Mageshwaran D', email: 'umamageshwaran.28csb@licet.ac.in', password: 'umamageshwaran28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Valencea A', email: 'valencea.28csb@licet.ac.in', password: 'valencea28csb@licet', section: 'II CSE-B', year: 2 },
  { name: 'Willi Carter Prabhu W', email: 'willicarterprabhu.28csb@licet.ac.in', password: 'willicarterprabhu28csb@licet', section: 'II CSE-B', year: 2 },
  // III CSE-A
  { name: 'Aaron Cruz Victor Morais', email: 'aaroncruzvictormorais.27csa@licet.ac.in', password: 'aaroncruzvictormorais27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Aditya A B', email: 'aditya.27csa@licet.ac.in', password: 'aditya27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Akash Ram K', email: 'akashram.27csa@licet.ac.in', password: 'akashram27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Alan Kishor S M', email: 'alankishor.27csa@licet.ac.in', password: 'alankishor27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Alexis Emmanuel Lopez D', email: 'alexisemmanuellopez.27csa@licet.ac.in', password: 'alexisemmanuellopez27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Allan Joe S', email: 'allanjoe.27csa@licet.ac.in', password: 'allanjoe27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Amy John', email: 'amyjohn.27csa@licet.ac.in', password: 'amyjohn27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Anbarasi S', email: 'anbarasi.27csa@licet.ac.in', password: 'anbarasi27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Anisha A', email: 'anisha.27csa@licet.ac.in', password: 'anisha27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Annal Santhiya S', email: 'annalsanthiya.27csa@licet.ac.in', password: 'annalsanthiya27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Antonita Evelyn Maria S', email: 'antonitaevelynmaria.27csa@licet.ac.in', password: 'antonitaevelynmaria27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Antoniya Jency J', email: 'antoniyajency.27csa@licet.ac.in', password: 'antoniyajency27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Aronsha A', email: 'aronsha.27csa@licet.ac.in', password: 'aronsha27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Aslam Siddhiq A', email: 'aslamsiddhiq.27csa@licet.ac.in', password: 'aslamsiddhiq27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Aswanth K', email: 'aswanth.27csa@licet.ac.in', password: 'aswanth27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Austin Stejoh A', email: 'austinstejoh.27csa@licet.ac.in', password: 'austinstejoh27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Brendan Wesley A', email: 'brendanwesley.27csa@licet.ac.in', password: 'brendanwesley27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Charles M S', email: 'charles.27csa@licet.ac.in', password: 'charles27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Chris Nikhil Fernando', email: 'chrisnikhilfernando.27csa@licet.ac.in', password: 'chrisnikhilfernando27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Danicaa Silva S', email: 'danicaasilva.27csa@licet.ac.in', password: 'danicaasilva27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Dany Brooks', email: 'danybrooks.27csa@licet.ac.in', password: 'danybrooks27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Darin Mario P', email: 'darinmario.27csa@licet.ac.in', password: 'darinmario27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Dhivya R', email: 'dhivya.27csa@licet.ac.in', password: 'dhivya27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Divina Francy R', email: 'divinafrancy.27csa@licet.ac.in', password: 'divinafrancy27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Durga S', email: 'durga.27csa@licet.ac.in', password: 'durga27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Duvvuru Pravanya Sree', email: 'duvvurupravanyasree.27csa@licet.ac.in', password: 'duvvurupravanyasree27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Eswar Raja S', email: 'eswarraja.27csa@licet.ac.in', password: 'eswarraja27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Evangeline Bettina Victoria H', email: 'evangelinebettinavictoria.27csa@licet.ac.in', password: 'evangelinebettinavictoria27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Evanglin Sharol S', email: 'evanglinsharol.27csa@licet.ac.in', password: 'evanglinsharol27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Ezhilmathi S', email: 'ezhilmathi.27csa@licet.ac.in', password: 'ezhilmathi27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Francis Roger A', email: 'francisroger.27csa@licet.ac.in', password: 'francisroger27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Franitha Ezhilmathi X', email: 'franithaezhilmathi.27csa@licet.ac.in', password: 'franithaezhilmathi27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Freddy Selvanathan G', email: 'freddyselvanathan.27csa@licet.ac.in', password: 'freddyselvanathan27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Gracelin A', email: 'gracelin.27csa@licet.ac.in', password: 'gracelin27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Hari Ram S', email: 'hariram.27csa@licet.ac.in', password: 'hariram27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Hemanth R', email: 'hemanth.27csa@licet.ac.in', password: 'hemanth27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Herson P', email: 'herson.27csa@licet.ac.in', password: 'herson27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Hilton Kennedy R', email: 'hiltonkennedy.27csa@licet.ac.in', password: 'hiltonkennedy27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Himani Chandra B', email: 'himanichandra.27csa@licet.ac.in', password: 'himanichandra27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Irene Gladiya P', email: 'irenegladiya.27csa@licet.ac.in', password: 'irenegladiya27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Irudhaya Rose A', email: 'irudhayarose.27csa@licet.ac.in', password: 'irudhayarose27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Isaac Kingsley D', email: 'isaackingsley.27csa@licet.ac.in', password: 'isaackingsley27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Isithore S', email: 'isithore.27csa@licet.ac.in', password: 'isithore27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Iyrin Priyadharshni A', email: 'iyrinpriyadharshni.27csa@licet.ac.in', password: 'iyrinpriyadharshni27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Jabez Ananias Paul K', email: 'jabezananiaspaul.27csa@licet.ac.in', password: 'jabezananiaspaul27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Janani R', email: 'janani.27csa@licet.ac.in', password: 'janani27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Jaron C E', email: 'jaron.27csa@licet.ac.in', password: 'jaron27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Jashua T', email: 'jashua.27csa@licet.ac.in', password: 'jashua27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Jeffery Ruban A', email: 'jefferyruban.27csa@licet.ac.in', password: 'jefferyruban27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Jency Rufina Mary A', email: 'jencyrufinamary.27csa@licet.ac.in', password: 'jencyrufinamary27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Jerosha Kumar K', email: 'jeroshakumar.27csa@licet.ac.in', password: 'jeroshakumar27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Joel Leon L', email: 'joelleon.27csa@licet.ac.in', password: 'joelleon27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Joel R', email: 'joel.27csa@licet.ac.in', password: 'joel27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Johanna Fernando P', email: 'johannafernando.27csa@licet.ac.in', password: 'johannafernando27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Joice Denicia S A', email: 'joicedenicia.27csa@licet.ac.in', password: 'joicedenicia27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Joshlin Mariya Leya F', email: 'joshlinmariyaleya.27csa@licet.ac.in', password: 'joshlinmariyaleya27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Joyel Immanuel L', email: 'joyelimmanuel.27csa@licet.ac.in', password: 'joyelimmanuel27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Karthikeyan S', email: 'karthikeyan.27csa@licet.ac.in', password: 'karthikeyan27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Kavipriya S', email: 'kavipriya.27csa@licet.ac.in', password: 'kavipriya27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Kaviya Gnana Varshini S A', email: 'kaviyagnanavarshini.27csa@licet.ac.in', password: 'kaviyagnanavarshini27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Keerthana N', email: 'keerthana.27csa@licet.ac.in', password: 'keerthana27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Keerthana S', email: 'keerthanas.27csa@licet.ac.in', password: 'keerthanas27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Keerthi Sebatina A', email: 'keerthisebatina.27csa@licet.ac.in', password: 'keerthisebatina27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'Kingsley J K', email: 'kingsley.27csa@licet.ac.in', password: 'kingsley27csa@licet', section: 'III CSE-A', year: 3 },
  { name: 'R Aarthi', email: 'aarthi.27csa@licet.ac.in', password: 'aarthi27csa@licet', section: 'III CSE-A', year: 3 },
  // III CSE-B
  { name: 'Kevin T', email: 'kevin.27csb@licet.ac.in', password: 'kevin27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Khalid M', email: 'khalid.27csb@licet.ac.in', password: 'khalid27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Kirush K', email: 'kirush.27csb@licet.ac.in', password: 'kirush27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Lakshmikanth S', email: 'lakshmikanth.27csb@licet.ac.in', password: 'lakshmikanth27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Lenora Rachel Xavier', email: 'lenorarachelxavier.27csb@licet.ac.in', password: 'lenorarachelxavier27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Levea Deroshen S', email: 'leveaderoshen.27csb@licet.ac.in', password: 'leveaderoshen27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Lourdh Sanya C', email: 'lourdhsanya.27csb@licet.ac.in', password: 'lourdhsanya27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Lumena U', email: 'lumena.27csb@licet.ac.in', password: 'lumena27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Mahesh Bharathi K', email: 'maheshbharathi.27csb@licet.ac.in', password: 'maheshbharathi27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Maria Jenova S', email: 'mariajenova.27csb@licet.ac.in', password: 'mariajenova27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Maria Sherlin A', email: 'mariasherlin.27csb@licet.ac.in', password: 'mariasherlin27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Marie Shalini S', email: 'marieshalini.27csb@licet.ac.in', password: 'marieshalini27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Martina K', email: 'martina.27csb@licet.ac.in', password: 'martina27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Mathan Kumaar A', email: 'mathankumaar.27csb@licet.ac.in', password: 'mathankumaar27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Mathesh S', email: 'mathesh.27csb@licet.ac.in', password: 'mathesh27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Mistika', email: 'mistika.27csb@licet.ac.in', password: 'mistika27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Monitta Sybia R V', email: 'monittasybia.27csb@licet.ac.in', password: 'monittasybia27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Narayanan D', email: 'narayanan.27csb@licet.ac.in', password: 'narayanan27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Naveen R S', email: 'naveen.27csb@licet.ac.in', password: 'naveen27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Neona Josh M', email: 'neonajosh.27csb@licet.ac.in', password: 'neonajosh27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Nerain Prakash I J', email: 'nerainprakash.27csb@licet.ac.in', password: 'nerainprakash27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Nithish Jude J', email: 'nithishjude.27csb@licet.ac.in', password: 'nithishjude27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Olivia Mary I', email: 'oliviamary.27csb@licet.ac.in', password: 'oliviamary27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Pavitara S', email: 'pavitara.27csb@licet.ac.in', password: 'pavitara27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Pooja Marcus P', email: 'poojamarcus.27csb@licet.ac.in', password: 'poojamarcus27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Pradeepraj Simon B', email: 'pradeeprajsimon.27csb@licet.ac.in', password: 'pradeeprajsimon27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Prakash R', email: 'prakash.27csb@licet.ac.in', password: 'prakash27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Pravalika P', email: 'pravalika.27csb@licet.ac.in', password: 'pravalika27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Praveen B', email: 'praveen.27csb@licet.ac.in', password: 'praveen27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Preethi K', email: 'preethi.27csb@licet.ac.in', password: 'preethi27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Prem Sai Subramanian M', email: 'premsaisubramanian.27csb@licet.ac.in', password: 'premsaisubramanian27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Priyadharshan S', email: 'priyadharshan.27csb@licet.ac.in', password: 'priyadharshan27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Quincy J Pullockara', email: 'quincyjpullockara.27csb@licet.ac.in', password: 'quincyjpullockara27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Rajarajeswari K', email: 'rajarajeswari.27csb@licet.ac.in', password: 'rajarajeswari27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Reina C', email: 'reina.27csb@licet.ac.in', password: 'reina27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Reni Benidita F', email: 'renibenidita.27csb@licet.ac.in', password: 'renibenidita27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Rohan Rooswelt P', email: 'rohanrooswelt.27csb@licet.ac.in', password: 'rohanrooswelt27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Rohit Amal Raj A', email: 'rohitamalraj.27csb@licet.ac.in', password: 'rohitamalraj27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Russel Sasmith R', email: 'russelsasmith.27csb@licet.ac.in', password: 'russelsasmith27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Safiya Fathima M', email: 'safiyafathima.27csb@licet.ac.in', password: 'safiyafathima27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Sahana Vincy J', email: 'sahanavincy.27csb@licet.ac.in', password: 'sahanavincy27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Sakthivel R', email: 'sakthivel.27csb@licet.ac.in', password: 'sakthivel27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Sam Gilchrist V', email: 'samgilchrist.27csb@licet.ac.in', password: 'samgilchrist27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Sam Rapheal S', email: 'samrapheal.27csb@licet.ac.in', password: 'samrapheal27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Samuel Dharshi N', email: 'samueldharshi.27csb@licet.ac.in', password: 'samueldharshi27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Samuthira K', email: 'samuthira.27csb@licet.ac.in', password: 'samuthira27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Sania R', email: 'sania.27csb@licet.ac.in', password: 'sania27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Sanjay Christopher Raj P', email: 'sanjaychristopherraj.27csb@licet.ac.in', password: 'sanjaychristopherraj27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Sanjay J', email: 'sanjay.27csb@licet.ac.in', password: 'sanjay27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Shane Joans', email: 'shanejoans.27csb@licet.ac.in', password: 'shanejoans27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Shanuka Roshni S', email: 'shanukaroshni.27csb@licet.ac.in', password: 'shanukaroshni27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Sharnika S', email: 'sharnika.27csb@licet.ac.in', password: 'sharnika27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Sharon Sophia C', email: 'sharonsophia.27csb@licet.ac.in', password: 'sharonsophia27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Sherwin Emmanuel Rodriguez P', email: 'sherwinemmanuelrodriguez.27csb@licet.ac.in', password: 'sherwinemmanuelrodriguez27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Shiphrah Jasmine J', email: 'shiphrahjasmine.27csb@licet.ac.in', password: 'shiphrahjasmine27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Smithaa S Krishna', email: 'smithaaskrishna.27csb@licet.ac.in', password: 'smithaaskrishna27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Sricharan V', email: 'sricharan.27csb@licet.ac.in', password: 'sricharan27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Srimathi S', email: 'srimathi.27csb@licet.ac.in', password: 'srimathi27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Stany Thomas', email: 'stanythomas.27csb@licet.ac.in', password: 'stanythomas27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Stephania Clarice A S', email: 'stephaniaclarice.27csb@licet.ac.in', password: 'stephaniaclarice27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Steven Daniel L', email: 'stevendaniel.27csb@licet.ac.in', password: 'stevendaniel27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Tejaswini M', email: 'tejaswini.27csb@licet.ac.in', password: 'tejaswini27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Thameemul Azarudeen N', email: 'thameemulazarudeen.27csb@licet.ac.in', password: 'thameemulazarudeen27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Tivona Kristina Thomas', email: 'tivonakristinathomas.27csb@licet.ac.in', password: 'tivonakristinathomas27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Vanesa Ann Vincent', email: 'vanesaannvincent.27csb@licet.ac.in', password: 'vanesaannvincent27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Vineet Jonathan C', email: 'vineetjonathan.27csb@licet.ac.in', password: 'vineetjonathan27csb@licet', section: 'III CSE-B', year: 3 },
  { name: 'Yuvanraj R', email: 'yuvanraj.27csb@licet.ac.in', password: 'yuvanraj27csb@licet', section: 'III CSE-B', year: 3 },
]

async function seed() {
  console.log(`Starting seed... ${STAFF.length} staff + ${STUDENTS.length} students`)

  for (const s of STAFF) {
    const { data, error } = await supabase.auth.admin.createUser({ email: s.email, password: s.password, email_confirm: true })
    if (error) { console.log(`SKIP ${s.email}: ${error.message}`); continue }
    if (!data.user) continue
    const { error: pe } = await supabase.from('profiles').upsert({
      id: data.user.id, role: s.role, department_id: DEPT_ID,
      full_name: s.name, email: s.email, employee_id: s.empId, is_active: true
    })
    if (pe) console.log(`Profile err ${s.email}: ${pe.message}`)
    else console.log(`✓ ${s.role}: ${s.name}`)
  }

  for (const st of STUDENTS) {
    const { data, error } = await supabase.auth.admin.createUser({ email: st.email, password: st.password, email_confirm: true })
    if (error) { console.log(`SKIP ${st.email}: ${error.message}`); continue }
    if (!data.user) continue
    const { error: pe } = await supabase.from('profiles').upsert({
      id: data.user.id, role: 'STUDENT', department_id: DEPT_ID,
      full_name: st.name, email: st.email, section: st.section,
      batch_year: st.year, is_active: true
    })
    if (pe) console.log(`Profile err ${st.email}: ${pe.message}`)
    else console.log(`✓ Student: ${st.name}`)
  }

  console.log('Seed complete!')
}

seed().catch(console.error)
